/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chat;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel
 */
public class novo_contato extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement ps = null;
    Statement st = null;
    ResultSet rs = null;
    
    public novo_contato() {
        initComponents();
    }
    int id;
    String usuario;
    novo_contato(String usuario,int id) {
        initComponents();
        this.id = id;
        this.usuario = usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        novo_contato = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nome_contato = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        email_contato = new javax.swing.JTextField();
        voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        novo_contato.setText("Salvar Contato");
        novo_contato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novo_contatoActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome Do Contato");

        jLabel2.setText("Email Contato");

        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(voltar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(novo_contato))
                            .addComponent(nome_contato, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(email_contato, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nome_contato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(email_contato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(novo_contato)
                    .addComponent(voltar))
                .addContainerGap(159, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        new contato(usuario,id).setVisible(true);
        dispose();
    }//GEN-LAST:event_voltarActionPerformed

    private void novo_contatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novo_contatoActionPerformed
        try{
            conn = dbConnections.getConnection();
            
            
            st = conn.createStatement();
            rs = st.executeQuery("SELECT * FROM LOGIN WHERE EMAIL = '" + email_contato.getText() + "'");
            while(rs.next()){
                System.out.println(rs.getInt("ID") + ", " + rs.getString("NOME") 
                        + ", " + rs.getString("SENHA") + ", " 
                        + rs.getString("EMAIL"));
                if(nome_contato.getText().length() >= 5 && email_contato.getText().length() >= 10){     
                    ps = conn.prepareStatement("INSERT INTO CONTATOS "
                                            + "(ID_CRIADOR,NOME_CONTATO,ID_CONTATO) "
                                            + "VALUES "
                                            + "(?,?,?)");
                    ps.setInt(1, id);
                    ps.setString(2, nome_contato.getText().toLowerCase());
                    ps.setInt(3, rs.getInt("ID"));
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Contato Salvo", "Sucesso", JOptionPane.DEFAULT_OPTION);
                
                }
                else{
                    JOptionPane.showMessageDialog(null, "Não Foi possivel Cadastrar o contato", "Erro", JOptionPane.ERROR_MESSAGE);
                }
            }

            
        }
        catch(SQLException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Não Foi possivel Cadastrar o contato", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        finally{
//            dbConnections.closeStatement(ps);
//            dbConnections.closeConnection();
            
        }
    }//GEN-LAST:event_novo_contatoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(novo_contato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(novo_contato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(novo_contato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(novo_contato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new novo_contato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email_contato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField nome_contato;
    private javax.swing.JButton novo_contato;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
